# Generated by jPipe
# Source : release.jd
# Date   : 2026-07-19T00:33:14.535599Z

import os
from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]

@jpipe_link("release:e1")
@jpipe(produce=["tests_pass"])
def the_test_suite_passes(produce: JpipeProduce) -> bool:
    """[evidence] The test suite passes"""
    result = os.path.isfile("mock/tests.ok")   # your real check goes here
    produce("tests_pass", result)
    return result

@jpipe_link("release:e2")
@jpipe(produce=["changelog_ok"])
def the_changelog_is_up_to_date(produce: JpipeProduce) -> bool:
    """[evidence] The changelog is up to date"""
    with open("mock/CHANGELOG.md") as f:
        result = "2.0" in f.read()   # the changelog names this release
    produce("changelog_ok", result)
    return result

@jpipe_link("release:s")
@jpipe(consume=["tests_pass", "changelog_ok"])
def all_release_gates_pass(tests_pass: bool, changelog_ok: bool) -> bool:
    """[strategy] All release gates pass"""
    return tests_pass and changelog_ok